# Generated by Django 5.2.6 on 2025-09-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='segment_text',
            field=models.TextField(blank=True, help_text='Text content from the video segment', null=True),
        ),
    ]
