# Generated by Django 5.2.6 on 2025-09-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_segment_text_to_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='processing_status',
            field=models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploading', help_text='Current processing status', max_length=20),
        ),
    ]
